// <auto-generated />
using System;
using FacturaTallerMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FacturaTallerMVC.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("FacturaTallerMVC.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FacturaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("FacturaTallerMVC.Models.Coche", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Combustible")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FacturaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kilometros")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Matricula")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FacturaId");

                    b.ToTable("Coches");
                });

            modelBuilder.Entity("FacturaTallerMVC.Models.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<float>("Neto")
                        .HasColumnType("REAL");

                    b.Property<int>("Pvp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Trabajo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Unidades")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("FacturaTallerMVC.Models.Recambio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FacturaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Precio")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.ToTable("Recambios");
                });

            modelBuilder.Entity("FacturaTallerMVC.Models.Cliente", b =>
                {
                    b.HasOne("FacturaTallerMVC.Models.Factura", null)
                        .WithMany("Clientes")
                        .HasForeignKey("FacturaId");
                });

            modelBuilder.Entity("FacturaTallerMVC.Models.Coche", b =>
                {
                    b.HasOne("FacturaTallerMVC.Models.Cliente", null)
                        .WithMany("Coches")
                        .HasForeignKey("ClienteId");

                    b.HasOne("FacturaTallerMVC.Models.Factura", null)
                        .WithMany("Coches")
                        .HasForeignKey("FacturaId");
                });

            modelBuilder.Entity("FacturaTallerMVC.Models.Recambio", b =>
                {
                    b.HasOne("FacturaTallerMVC.Models.Factura", null)
                        .WithMany("Recambios")
                        .HasForeignKey("FacturaId");
                });

            modelBuilder.Entity("FacturaTallerMVC.Models.Cliente", b =>
                {
                    b.Navigation("Coches");
                });

            modelBuilder.Entity("FacturaTallerMVC.Models.Factura", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Coches");

                    b.Navigation("Recambios");
                });
#pragma warning restore 612, 618
        }
    }
}
